### ISSUE TITLE
Request to backfill Buildhub Data

### ISSUE THREAD

**Issue by fbertsch** [mozilla-releng/buildhub2#502]
We use Buildhub to scrape historical revisions of the probe definitions files in the [probe scraper.](https://www.github.com/mozilla/probe-scraper) We scrape `json-nodes` for everything back to version 30; would it be possible to include versions back until then? This is preventing us from [switching over to Buildhub instead of scraping the `json-nodes` files.](https://github.com/mozilla/probe-scraper/issues/71)

More immediately, it is blocking merging https://github.com/mozilla/probe-scraper/pull/66.

**Comment by fbertsch** [comment]
Version 30 comes from here: https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/scrapers/moz_central_scraper.py#L44.

**Comment by peterbe** [comment]
Buildhub2 has all the data Buildhub1 has. If that doesn't go back to to version 30 and if version 30 is not in archive.mozilla.org then I don't know what's up.

As a matter of fact; https://archive.mozilla.org/pub/firefox/releases/30.0/ exists but only version 30.0a1 is available on Buildhub1 https://mozilla-services.github.io/buildhub/?q=firefox%2030

Remember, Buildhub2 is significantly different than Buildhub1 in that Buildhub1 would try to scrape archive.mozilla.org and *attempt* to piece together all the necessary data. 
In Buildhub2 instead, there is not and never will be scraping. Well, technically it's still scraping but it's only ever exactly the `*buildhub.json` files in archive.mozilla.org and the creation of these files is done by TaskCluster. No `*buildhub.json`, no record in Buildhub2 (buildhub.moz.tools). 

https://buildhub2.readthedocs.io/en/latest/architecture.html#first-principles

I feel like a bit arrogant for saying this but we won't do any backfill scraping.

**Comment by peterbe** [comment]
For what it's worth, today Buildhub2's only ongoing input stream is a SQS queue filled from S3 Events. When TaskCluster uploads files to S3 (e.g. setup.ext and buildhub.json) it triggers a notification to Buildhub2 which then proceeds to download it from S3 (so, not really scraping in the traditional sense of downloading HTML and parsing it). 

Buildhub2 has an untested script which is able to iterate over every single file in S3 (mirrored by archive.mozilla.org). It just loops over all directories and looks for `*buildhub.json` files. So, if you could convince someone to retrofit a `buildhub.json` in a directory like https://archive.mozilla.org/pub/firefox/releases/30.0/win32/en-US/ it could get picked up.

**Comment by fbertsch** [comment]
@peterbe what is the format of the `buildhub.json` files?

**Comment by peterbe** [comment]
Example: https://archive.mozilla.org/pub/firefox/nightly/2019/02/2019-02-22-08-11-12-mozilla-central/firefox-67.0a1.en-US.linux-i686.buildhub.json

And here's the schema: https://github.com/mozilla/buildhub2/blob/master/schema.yaml

Sadly, I think this schema isn't enforced or synchronized in the mozilla-central code that generates the buildhub.json files.

**Comment by willkg** [comment]
@fbertsch I hit a similar problem with Socorro last year. What's going on is that Buildhub, Buildhub2, and Socorro all get their data from archive.mozilla.org. archive.mozilla.org purged the build data for Firefox prior to 50 (I think it's actually based on date--not version).

I talked to Callek about it at All Hands December 2018 and came away from the conversation thinking the missing build data is gone forever. Maybe that's not totally true and we can resurrect it from some other data source--I don't know. Seems like a big project.

Anyhow, anything that's not in Buildub/Buildhub2 is probably not something we can add unless you have a new information source. If you do, I can probably figure out how to add it manually.

**Comment by mozbhearsum** [comment]
It sounds like there's no way to proceed on this issue. I'm going to close it, but I'm happy to re-open it if I've missed something.
